name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- KROK DIAGNOSTYCZNY 1: Pokaż, co jest w pliku PRZED zmianą ---
      - name: Verify config.js content (before replacement)
        run: |
          echo "--- Content of js/config.js BEFORE replacement ---"
          cat js/config.js
          echo "----------------------------------------------------"

      - name: Inject GitHub Token
        run: |
          sed -i 's|__GH_TOKEN__|${{ secrets.GH_TOKEN }}|g' js/config.js

      # --- KROK DIAGNOSTYCZNY 2: Pokaż, co jest w pliku PO zmianie ---
      - name: Verify config.js content (after replacement)
        run: |
          echo "--- Content of js/config.js AFTER replacement ---"
          cat js/config.js
          echo "---------------------------------------------------"

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
